#!/bin/sh

DEVICE=/dev/video4

v4l2-ctl --device=$DEVICE \
  --set-fmt-video=width=1920,height=1080,pixelformat=YUYV \
  >/dev/null 2>&1

exec ffplay \
  -f v4l2 \
  -input_format yuyv422 \
  -video_size 1920x1080 \
  -framerate 60 \
  -fast \
  $DEVICE
